export declare const epsilon: number;
export type DiceMode = 'standard' | 'lowluck' | 'biased';
export type SortMode = 'unit_count' | 'ipc_cost';
export type PwinMode = 'takes' | 'destroys';
import { general_unit_group, unit_manager } from './unitgroup.js';
import { type casualty_1d } from './output.js';
export declare class general_problem {
    um: unit_manager;
    is_naval: boolean;
    prob: number;
    att_data: general_unit_group;
    def_data: general_unit_group;
    is_nonaval: boolean;
    is_retreat: boolean;
    is_amphibious: boolean;
    is_crash_fighters: boolean;
    rounds: number;
    average_rounds: number;
    diceMode: DiceMode;
    sortMode: SortMode;
    is_deadzone: boolean;
    skip_compute: boolean;
    territory_value: number;
    retreat_round_zero: boolean;
    do_roundless_eval: boolean;
    N: number;
    M: number;
    debug_level: number;
    verbose_level: number;
    ERound_1d: number[];
    init_rounds: number;
    P_1d: number[];
    is_retreat_state_initialized: boolean;
    R_1d: boolean[];
    E_1d: number[];
    accumulate: number;
    base_attcost: number;
    base_defcost: number;
    pwin_acc: number;
    Pwin_1d: number[];
    nonavalproblem: general_problem | undefined;
    def_cas: casualty_1d[] | undefined;
    prune_threshold: number;
    early_prune_threshold: number;
    report_prune_threshold: number;
    retreat_threshold: number;
    retreat_expected_ipc_profit_threshold?: number;
    retreat_pwin_threshold?: number;
    pwinMode?: PwinMode;
    retreat_strafe_threshold?: number;
    retreat_lose_air_probability: number;
    attmap: Map<string, number>;
    defmap: Map<string, number>;
    attmap2: Map<string, number>;
    defmap2: Map<string, number>;
    getIndex(i: number, j: number): number;
    getiP(ii: number): number;
    getP(i: number, j: number): number;
    setiP(ii: number, val: number): void;
    setP(i: number, j: number, val: number): void;
    getiE(ii: number): number;
    setiE(ii: number, val: number): void;
    getE(i: number, j: number): number;
    setE(i: number, j: number, val: number): void;
    setPwin(i: number, j: number, val: number): void;
    getiPwin(ii: number): number;
    getPwin(i: number, j: number): number;
    setiPwin(ii: number, val: number): void;
    getiERound(ii: number): number;
    setiERound(ii: number, val: number): void;
    getERound(i: number, j: number): number;
    setERound(i: number, j: number, val: number): void;
    getRetreat(i: number, j: number): boolean;
    getiRetreat(ii: number): boolean;
    setRetreat(i: number, j: number, val: boolean): void;
    setiRetreat(ii: number, val: boolean): void;
    set_prune_threshold(pt: number, ept: number, rpt: number): void;
    isEarlyRetreat(): boolean;
    hasRetreatCondition(): boolean;
    hasNonCombat(): boolean;
    get_complexity(): number;
    constructor(verbose_level: number, um: unit_manager, att_str: string, def_str: string, prob: number, att_dest_last: boolean, att_submerge: boolean, def_dest_last: boolean, def_submerge: boolean, rounds: number, retreat_threshold: number, is_crash_fighters: boolean, is_naval: boolean | undefined, def_cas: casualty_1d[] | undefined, is_nonaval: boolean | undefined, diceMode: DiceMode | undefined, sortMode: SortMode | undefined, is_deadzone: boolean | undefined, skip_compute: boolean | undefined, territory_value: number | undefined, retreat_round_zero: boolean | undefined, do_roundless_eval: boolean | undefined, retreat_lose_air_probability: number, retreat_expected_ipc_profit_threshold?: number, retreat_pwin_threshold?: number, pwinMode?: PwinMode, retreat_strafe_threshold?: number);
    setNoNavalP(N1: number, M1: number, N2: number, M2: number, p: number): void;
}
export declare function is_retreat_state(problem: general_problem, N: number, M: number): boolean;
export declare function compute_retreat_state(problem: general_problem): void;
export declare function compute_expected_value(problem: general_problem): void;
export declare function compute_prob_wins(problem: general_problem): void;
export declare function do_round_eval(problem: general_problem, allow_same_state: boolean, num_bombard: number, do_retreat_only: boolean, disable_retreat: boolean): void;
export declare function solve_general(problem: general_problem): void;
//# sourceMappingURL=solve.d.ts.map